### ISSUE TITLE
no logic  was found for copy-trade

### ISSUE THREAD

**Issue by ignoracenfly** [maxwell-dev-sol/solana-volume-bot#1]
no logic  was found for copy-trade

**Comment by maxwell-dev-sol** [comment]
he bot supports copy-trading, wallet parsing, and analysis features.
It can also monitor wallets you're interested in and notify you in Discord or Telegram about all changes.
There's logic to it;)

**Comment by maxwell-dev-sol** [comment]
bot supports copy-trading, wallet parsing, and analysis features.
It can also monitor wallets you're interested in and notify you in Discord or Telegram about all changes.
There's logic to it;)
